from tkinter import *
import tkinter as tk
from tkinter import messagebox

window = Tk()
window.geometry("1100x900")
window.title("Car Rental Receipt" )

title = Label(window,text="CAR RENTAL RECEIPT",font=("Calibri \
Bold",30),anchor=N).grid(row=0,column=2)
date = Label(window,text="DATE:- ").grid(row=3,column=0)
date = Entry(window)
date.grid(row=3,column=1)
receipt = Label(window,text="RECEIPT#:- ").grid(row=3,column=3)
receipt = Entry(window)
receipt.grid(row=3,column=4)
subhd1 = Label(window,text="COMPANY INFO",font=("Calibri \
Bold",16)).grid(row=7,column=1)
company = Label(window,text="COMPANY:- ").grid(row=9,column=0)
company = Entry(window)
company.grid(row=9,column=1)
rep = Label(window,text="REPRESENTATIVE:-").grid(row=10,column=0)
rep = Entry(window)
rep.grid(row=10,column=1)
loc = Label(window,text="LOCATION:-").grid(row=11,column=0)
loc = Entry(window)
loc.grid(row=11,column=1)
csz = Label(window,text="CITY/STATE/ZIP:-").grid(row=12,column=0)
csz = Entry(window)
csz.grid(row=12,column=1)
phone = Label(window,text="PHONE:-").grid(row=13,column=0)
phone = Entry(window)
phone.grid(row=13,column=1)
subhd2 = Label(window,text="LESSEE INFO",font=("Calibri \
Bold",16)).grid(row=7,column=4)
name = Label(window,text="NAME:-").grid(row=9,column=3)
name = Entry(window)
name.grid(row=9,column=4)
license = Label(window,text="LICENSE#:-").grid(row=10,column=3)
license = Entry(window)
license.grid(row=10,column=4)
address = Label(window,text="ADDRESS:-").grid(row=11,column=3)
address = Entry(window)
address.grid(row=11,column=4)
csz1 = Label(window,text="CITY/STATE/ZIP:-").grid(row=12,column=3)
csz1 = Entry(window)
csz1.grid(row=12,column=4)
phone1 = Label(window,text="PHONE:-").grid(row=13,column=3)
phone1 = Entry(window)
phone.grid(row=13,column=4)
vi = Label(window,text="VEHICLE INFORMATION",font=("Calibri \
Bold",26)).grid(row=16,column=2)
VIN1 = Label(window,text="VIN:-").grid(row=18,column=0)
VIN1 = Entry(window)
VIN1.grid(row=18,column=1)
make = Label(window,text="MAKE:-").grid(row=19,column=0)
make = Entry(window)
make.grid(row=19,column=1)
year = Label(window,text="YEAR:-").grid(row=20,column=0)
year = Entry(window)
year.grid(row=20,column=1)
color = Label(window,text="COLOR:-").grid(row=21,column=0)
color = Entry(window)
color.grid(row=21,column=1)
reg = Label(window,text="REGISTRATION#:-").grid(row=18,column=3)
reg = Entry(window)
reg.grid(row=18,column=4)
model = Label(window,text="MODEL:-").grid(row=19,column=3)
model = Entry(window)
model.grid(row=19,column=4)
milg = Label(window,text="MILEAGE:-").grid(row=20,column=3)
milg = Entry(window)
milg.grid(row=20,column=4)
VIN = Label(window,text="VIN",font=("Calibri \
Bold",16)).grid(row=50,column=0)
cd = Label(window,text="COST/DAY",font=("Calibri \
Bold",16)).grid(row=50,column=1)
of = Label(window,text="OF DAYS#",font=("Calibri \
Bold",16)).grid(row=50,column=2)
ac = Label(window,text="ADDITIONAL COST",font=("Calibri \
Bold",16)).grid(row=50,column=3)
lc = Label(window,text="LINE COST",font=("Calibri \
Bold",16)).grid(row=50,column=4)
pm = Label(window,text="PAYMENT METHOD:-",font=("Calibri \
Bold",14)).grid(row=57,column=0)
st = Label(window,text="SUBTOTAL:-",font=("Calibri",14)).grid(row=57,column=2)
st = Entry(window).grid(row=57,column=3)
tax= Label(window,text="TAX(5%):-",font=("Calibri",12)).grid(row=58,column=2)
tax = Entry(window)
tax.grid(row=58,column=3)
total= Label(window,text="TOTAL:-",font=("Calibri",12)).grid(row=59,column=2)
total= Entry(window)
total.grid(row=59,column=3)
ap = Label(window,text="AMOUNT PAID:-",font=("Calibri",12)).grid(row=60,column=2)
ap = Entry(window)
ap.grid(row=60,column=3)
sig = Label(window,text="AUTHORIZED \
SIGNATURE:-",font=("Calibri",12)).grid(row=62,column=3)
sig = Entry(window)
sig.grid(row=62,column=4)
rp_name = Label(window,text="REPRESENTATIVE \
NAME:-",font=("Calibri",12)).grid(row=63,column=3)
rp_name = Entry(window)
rp_name.grid(row=63,column=4)
a=Checkbutton(window,text="CASH:-",font=("Calibri",12)).grid(row=58,column=0)
b=Checkbutton(window,text="DEBIT:-",font=("Calibri",12)).grid(row=59,column=0)
c=Checkbutton(window,text="CREDIT:-",font=("Calibri",12)).grid(row=60,column=0)
d=Checkbutton(window,text="OTHER:-",font=("Calibri",12)).grid(row=61,column=0)
cash=Entry(window)
cash.grid(row=58,column=1)
deb=Entry(window)
deb.grid(row=59,column=1)
cred=Entry(window)
cred.grid(row=60,column=1)
oth=Entry(window)
oth.grid(row=61,column=1)
e=Entry(window)
e.grid(row=51,column=0)
f=Entry(window)
f.grid(row=52,column=0)
g=Entry(window)
g.grid(row=53,column=0)
h=Entry(window)
h.grid(row=51,column=1)
i=Entry(window)
i.grid(row=52,column=1)
j=Entry(window)
j.grid(row=53,column=1)
k=Entry(window)
k.grid(row=51,column=2)
l=Entry(window)
l.grid(row=52,column=2)
m=Entry(window)
m.grid(row=53,column=2)
n=Entry(window)
n.grid(row=51,column=3)
o=Entry(window)
o.grid(row=52,column=3)
p=Entry(window)
p.grid(row=53,column=3)
q=Entry(window)
q.grid(row=51,column=4)
r=Entry(window)
r.grid(row=52,column=4)
s=Entry(window)
s.grid(row=53,column=4)
t=Entry(window)
t.grid(row=54,column=4)
u=Entry(window)
u.grid(row=55,column=4)
v=Entry(window)
v.grid(row=56,column=4)
w=Entry(window)
w.grid(row=60,column=4)
msg=Button(window, text='SUBMIT',width=20).place(x=350,y=700)
msg=Button(window,text="DISPLAY \
RECORD(s)",width=20).place(x=550,y=700)
window.mainloop()






